# Generated by Django 2.1.11 on 2019-09-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_representation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_published',
            field=models.PositiveIntegerField(),
        ),
    ]
