# Generated by Django 2.1.11 on 2019-11-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_representation', '0003_auto_20191112_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_published',
            field=models.CharField(max_length=140),
        ),
    ]
