# Generated by Django 2.1.11 on 2019-11-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_representation', '0004_auto_20191112_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='wiki_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
