# Generated by Django 2.1.11 on 2019-11-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_representation', '0005_auto_20191112_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_published',
            field=models.PositiveIntegerField(),
        ),
    ]
